// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAknVNh4fjc2PlD9AWkCEviBVNjplRzUYk',
    appId: '1:549748286521:web:93b487f53c19137d2359e8',
    messagingSenderId: '549748286521',
    projectId: 'nooreen2026',
    authDomain: 'nooreen2026.firebaseapp.com',
    storageBucket: 'nooreen2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0rCjQ6Ia5sNfxsOBAg9NhbQwlOY-bcn8',
    appId: '1:549748286521:android:601d1c7aadc92f682359e8',
    messagingSenderId: '549748286521',
    projectId: 'nooreen2026',
    storageBucket: 'nooreen2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjNFLEARtMmt5J1G4XLyKtJd86P9_IumM',
    appId: '1:549748286521:ios:c6eb50d7143cbf5e2359e8',
    messagingSenderId: '549748286521',
    projectId: 'nooreen2026',
    storageBucket: 'nooreen2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjNFLEARtMmt5J1G4XLyKtJd86P9_IumM',
    appId: '1:549748286521:ios:c6eb50d7143cbf5e2359e8',
    messagingSenderId: '549748286521',
    projectId: 'nooreen2026',
    storageBucket: 'nooreen2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAknVNh4fjc2PlD9AWkCEviBVNjplRzUYk',
    appId: '1:549748286521:web:4aea6d8a1e08a50d2359e8',
    messagingSenderId: '549748286521',
    projectId: 'nooreen2026',
    authDomain: 'nooreen2026.firebaseapp.com',
    storageBucket: 'nooreen2026.firebasestorage.app',
  );
}
